...started at Fri Jul 23 21:22:42 EDT 2021

======================================
  MutSigCV
  v1.4

  (c) Mike Lawrence and Gaddy Getz
  Broad Institute of MIT and Harvard
======================================


MutSigCV: PREPROCESS
--------------------
Loading mutation_file...
Error using MutSigCV_nbg>MutSig_preprocess (line 246)
MutSig is not applicable to single patients.\n

Error in MutSigCV_nbg (line 184)
  MutSig_preprocess(mutation_file,coverage_file,covariate_file,output_filestem,varargin{:})

Bone-Benign
Traceback (most recent call last):
  File "run_histology_nsyn.py", line 37, in <module>
    runMutSigCV_nsyn(feat)
  File "run_histology_nsyn.py", line 34, in runMutSigCV_nsyn
    eng.MutSigCV_nbg(maf,cov, covariates, outp, mut_dic, chain_f, nargout = 0)
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File /gpfs/group/epo2/default/yur97/gitlab/pcawg-to-mutsigcv/mutsig/MutSigCV_nbg.m, line 246, in MutSig_preprocess

  File /gpfs/group/epo2/default/yur97/gitlab/pcawg-to-mutsigcv/mutsig/MutSigCV_nbg.m, line 184, in MutSigCV_nbg
MutSig is not applicable to single patients.\n

...ended at Fri Jul 23 21:23:06 EDT 2021
